# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название изображения')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Gallery/')),
            ],
            options={
                'ordering': ['site', 'name'],
                'verbose_name_plural': 'Gallery photo ',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название сайта')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageparser.Site', verbose_name='Сайт'),
        ),
    ]
